#!/bin/sh

if [ "$1" != "wrapped" ]; then
	exec /usr/bin/rlwrap "$0" wrapped
fi

/usr/bin/tail -F /etc/service/minecraft/log/main/current &
PID=$!

kill_it() {
	echo
	kill $PID
}
trap kill_it EXIT

cat > /etc/service/minecraft/input
